/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalKargo;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seda Demir
 */
public class kargoDurumGuncelle extends javax.swing.JFrame {

    /**
     * Creates new form kargoDurumGuncelle
     */
    public kargoDurumGuncelle() {
        initComponents();
        Connection conn = null;
        PreparedStatement psmt = null;        
        try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost/javadb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","1234");        
        String sorgu = "Select * From kTable";
        psmt =conn.prepareStatement(sorgu);
        ResultSet kayitlar = psmt.executeQuery();
        ResultSetMetaData rowdata = (ResultSetMetaData) kayitlar.getMetaData();
        int j =0;     
        int k = rowdata.getColumnCount();
        String[] kolon = new String[k];
        for( j=0; j<k; j++) {
        kolon[j] = rowdata.getColumnName(j+1);
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(new Object [][]{},new String []{}));
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setColumnIdentifiers(kolon);
        while(kayitlar.next()) {
        Object[] o = new Object[k];
        for(j=0; j<k; j++) {
        o[j] = kayitlar.getObject(j+1);
        }
        model.addRow(o);
        }
        jTable2.setModel(model);

        psmt.close();
        conn.close();
        }
       catch (SQLException se)
       {
       
       }
        try {         
            conn = DriverManager.getConnection("jdbc:mysql://localhost/javadb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","1234");
            ArrayList<String> groupNames = new ArrayList<>();
            String sorgu = "SELECT dDurum FROM dTable";
            psmt = conn.prepareStatement(sorgu);
            try (ResultSet rs = psmt.executeQuery(sorgu)) {
                while (rs.next()) {
                    String groupName = rs.getString("dDurum");
                    groupNames.add(groupName);
                }
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
            dDurumBox1.setModel(model);
            
        } catch (SQLException se) {
        } catch (Exception e) {

        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kIdTxt = new javax.swing.JTextField();
        kGuncelleBtn = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        dDurumBox = new javax.swing.JComboBox<>();
        dDurumBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Güncellemek istediğiniz kargonun ID'sini giriniz: ");
        jLabel1.setToolTipText("");

        kGuncelleBtn.setText("GÜNCELLE");
        kGuncelleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kGuncelleBtnActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "G.Tarihi", "Tahmini TT", "Kilo", "Nerede", "G.Şube", "A.Şube", "Durumu", " Fiyatı"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jScrollPane11.setViewportView(jTable2);

        jLabel2.setText("Yeni Durum:");

        dDurumBox.setMaximumRowCount(10);
        dDurumBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Durum Seçiniz" }));
        dDurumBox.setToolTipText("");
        dDurumBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDurumBoxActionPerformed(evt);
            }
        });

        dDurumBox1.setMaximumRowCount(10);
        dDurumBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Durum Seçiniz" }));
        dDurumBox1.setToolTipText("");
        dDurumBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dDurumBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dDurumBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kGuncelleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(220, 220, 220)
                    .addComponent(dDurumBox, 0, 258, Short.MAX_VALUE)
                    .addGap(221, 221, 221)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dDurumBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(kGuncelleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(dDurumBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
        );

        kIdTxt.getAccessibleContext().setAccessibleName("kargoGunelletxt");
        kGuncelleBtn.getAccessibleContext().setAccessibleName("kargoGuncellebtn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kGuncelleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kGuncelleBtnActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement psmt = null;
        int ID  = Integer.parseInt(kIdTxt.getText());
        int kDurum = dDurumBox1.getSelectedIndex()+1;
        try {         
            conn = DriverManager.getConnection("jdbc:mysql://localhost/javadb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","root","1234");
            String sGuncelle = " UPDATE kTable SET kDurumID = ? WHERE kID = ? ";
            /* Gönderici tablo ekleme kısmı */
            psmt = conn.prepareStatement(sGuncelle);            
            psmt.setInt (1,kDurum);
            psmt.setInt (2, ID);
            psmt.execute(); 
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Güncelleme işlemi başarılı.");
            psmt.close();
            conn.close();
            
        } catch (SQLException se) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Güncelleme işlemi başarısız.");
        } catch (Exception e) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Güncelleme işlemi başarısız.");
        }     
        
        
    }//GEN-LAST:event_kGuncelleBtnActionPerformed

    private void dDurumBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDurumBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dDurumBoxActionPerformed

    private void dDurumBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dDurumBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dDurumBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kargoDurumGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kargoDurumGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kargoDurumGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kargoDurumGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kargoDurumGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dDurumBox;
    private javax.swing.JComboBox<String> dDurumBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton kGuncelleBtn;
    private javax.swing.JTextField kIdTxt;
    // End of variables declaration//GEN-END:variables
}
